version: 2

updates:
    # Maintain dependencies for GitHub Actions
    - package-ecosystem: "github-actions"
      target-branch: "main"
      directory: "/"
      schedule:
          interval: "daily"
      labels:
          - "Actions"

    # Maintain dependencies for composer
    - package-ecosystem: "composer"
      target-branch: "main"
      directory: "src/"
      schedule:
          interval: "daily"
      labels:
          - "composer"
